### ISSUE TITLE
Error message: "ImportError: cannot import name 'testing_utils' from 'tests' (/home/rtagett/anaconda3/lib/python3.7/site-packages/tests/__init__.py)"

### ISSUE THREAD

**Issue by dkcoxie** [umich-brcf-bioinf/Watermelon#18]
Command used:
`(base) [rtagett@bfxcomp6app-prod01 Seedless_Mock_Report]$ /ccmb/BioinfCore/Common/pipelines/Watermelon/Watermelon-seedless/bin/watermelon_init --genome_build mm10 --sample_sheet pdat.csv --job_suffix Mock /ccmb/BioinfCore/DNASeqCore/Run_2523/preddy/Run_2523/preddy`

Error message:
`Traceback (most recent call last):
 File "/ccmb/BioinfCore/Common/pipelines/Watermelon/Watermelon-seedless/bin/watermelon_init", line 5, in <module>
  from scripts.watermelon_init import main
 File "/ccmb/BioinfCore/Common/pipelines/Watermelon/Watermelon-seedless/scripts/watermelon_init.py", line 52, in <module>
  from tests import testing_utils # Using gunzip_glob, maybe should move this to helper module?
ImportError: cannot import name 'testing_utils' from 'tests' (/home/rtagett/anaconda3/lib/python3.7/site-packages/tests/__init__.py)`

**Comment by dkcoxie** [comment]
*Solution*:     
* initialize watermelon conda environment with command `conda activate watermelon`
* update old 'mm10' reference tag to current ENSEMBL reference tag 'GRCm38'
